# Generated by Django 4.2 on 2023-05-08 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, choices=[('Dharavi STP', 'Dharavi STP'), ('UPJJM', 'UPJJM')], max_length=15)),
                ('division', models.CharField(blank=True, choices=[('Ayodhya (Amethi & Ambedkar Nagar)', 'Ayodhya (Amethi & Ambedkar Nagar)'), ('Jaunpur', 'Jaunpur'), ('Bulandshahr (Meerut division)', 'Bulandshahr (Meerut division)'), ('Sant Ravidas Nagar', 'Sant Ravidas Nagar')], max_length=40)),
                ('subject_line', models.CharField(blank=True, max_length=30)),
                ('date', models.DateField(auto_now=True)),
                ('summary', models.TextField(blank=True, max_length=50)),
                ('intimation', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(blank=True, max_length=20, null=True)),
                ('item_name', models.CharField(blank=True, max_length=20, null=True)),
                ('total_base_value', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity', models.CharField(blank=True, max_length=20, null=True)),
                ('unit_of_measurement', models.CharField(blank=True, max_length=10, null=True)),
                ('freight_charges', models.CharField(blank=True, max_length=10, null=True)),
                ('pf_charges', models.CharField(blank=True, max_length=10, null=True)),
                ('custom_duty', models.CharField(blank=True, max_length=10, null=True)),
                ('installation_charges', models.CharField(blank=True, max_length=10, null=True)),
                ('amc_charges', models.CharField(blank=True, max_length=10, null=True)),
                ('third_party_inspection_charges', models.CharField(blank=True, max_length=10, null=True)),
                ('other_charges', models.CharField(blank=True, max_length=10, null=True)),
                ('total_value', models.CharField(blank=True, max_length=10, null=True)),
                ('gst', models.CharField(blank=True, max_length=10, null=True)),
                ('landed_cost', models.CharField(blank=True, max_length=10, null=True)),
                ('delivery', models.CharField(blank=True, max_length=10, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=10, null=True)),
                ('remark', models.CharField(blank=True, max_length=50, null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NFAApp.entry')),
            ],
        ),
    ]
