# Generated by Django 4.2 on 2023-05-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NFAApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='project_name',
            field=models.CharField(max_length=15),
        ),
    ]
