# Generated by Django 4.2 on 2023-05-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NFAApp', '0003_remove_entry_intimation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='division',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
