# Generated by Django 4.2 on 2023-05-13 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NFAApp', '0012_entry_fillname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='FillName',
        ),
    ]
