# Generated by Django 4.2 on 2023-05-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NFAApp', '0013_remove_entry_fillname'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(blank=True, choices=[('Good', 'Good'), ('Neutral', 'Neutral'), ('Worse', 'Worse')], max_length=15)),
            ],
        ),
    ]
